spring:
  application:
    name: food-delivery

  profiles:
    active: dev, local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/deliv}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  servlet:
    context-path: /api
